image: ghcr.io/cirruslabs/flutter:stable

stages:
  - build

variables:
  ANDROID_SDK_ROOT: "/opt/android-sdk"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  paths:
    - .gradle/
    - build/

before_script:
  - flutter --version
  - flutter pub get

  # decode keystore
  - echo "$ANDROID_KEYSTORE" | base64 -d > android/app/keystore.jks
  - export ANDROID_KEYSTORE_PATH=android/app/keystore.jks

  # create entrypoints automatically
  - |
    cat > lib/main_dev.dart <<EOF
    import 'main.dart';
    void main() {
      const String flavor = 'dev';
      main();
    }
    EOF

  - |
    cat > lib/main_staging.dart <<EOF
    import 'main.dart';
    void main() {
      const String flavor = 'staging';
      main();
    }
    EOF

  - |
    cat > lib/main_prod.dart <<EOF
    import 'main.dart';
    void main() {
      const String flavor = 'prod';
      main();
    }
    EOF

build_dev:
  stage: build
  script:
    - flutter build appbundle --flavor dev -t lib/main_dev.dart
  artifacts:
    paths:
      - build/app/outputs/bundle/devRelease/
    expire_in: 1 week

build_staging:
  stage: build
  script:
    - flutter build appbundle --flavor staging -t lib/main_staging.dart
  artifacts:
    paths:
      - build/app/outputs/bundle/stagingRelease/
    expire_in: 1 week

build_prod:
  stage: build
  script:
    - flutter build appbundle --flavor prod -t lib/main_prod.dart
  artifacts:
    paths:
      - build/app/outputs/bundle/prodRelease/
    expire_in: 1 week